### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dogebi** [jmeviler/Metro-Weapp#1]
missing  the  data file

pls ，see  attach

![image](https://user-images.githubusercontent.com/25998022/52103548-25b66f00-2621-11e9-97c3-1b89359c97dd.png)

**Comment by jmeviler** [comment]
@dogebi 邮件已回复。

**Comment by dogebi** [comment]
@jmeviler  纯学习用， 麻烦邮件提供一下这两个么？  谢谢🙏

**Comment by jmeviler** [comment]
> @jmeviler 纯学习用， 麻烦邮件提供一下这两个么？ 谢谢🙏

已提交。再次感谢使用。
